---
# GitLab CI/CD pipeline 

stages:
   - deploy

variables:
    DOCKER_TLS_CERTDIR: ""

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo rm -rf /var/www/$CI_PROJECT_NAME"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo git clone --single-branch -b main $CI_REPOSITORY_URL /var/www/$CI_PROJECT_NAME"
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG != null
